### ISSUE TITLE
Ingress rules for landing page server

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/localdeploy#1]
## Issue Name

Ingress rules for landing page server

### Summary

Landing page server does not resolve direct links to resources e.g. from a DOI to a landing page.
Instead ingress returns 404 for all requests except to the root page.

### Steps to Reproduce

Attempt to resolve https://<landingpageserveraddress>/detail/12
should return 404

### Current Behaviour

https://<landingpageserveraddress>/detail/12
should return 404

### Expected Behaviour

https://<landingpageserveraddress>/detail/12
resolves to a landing page

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by garethcmurphy** [comment]
I found that the ingress rules for the landing page server for address like
 
https://kubetest03.dm.esss.dk:32223/detail/13
 
 
 
needs a regex in the ingress rules, plus a new annotation (to make it read the regex as a regex)
 
```
 nginx.ingress.kubernetes.io/rewrite-target: /
 ```
See (https://github.com/kubernetes/ingress-nginx/issues/619)

I’ve added the new rules to the dmscprod branch of localdeploy.
 
This works for the test cluster so hopefully it should work in production
The changes are below
 
services/landing/landingserver/templates/ingress.yaml
 
 ```
{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $namespace := .Release.Namespace -}}
{{- $host := .Values.ingress.host -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - secretName: landingserverservice
    hosts:
    - {{ $host }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          - path: /detail/(.*)
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{- end -}}
```
